default:
    image: node:alpine

build:
    stage: build
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - frontend/build
    script:
        - cd frontend
        - yarn install
        - yarn build
    
deploy-frontend:
    stage: deploy
    script:
        - npm install -g firebase-tools
        - cd frontend
        - firebase deploy --token "$FIREBASE_TOKEN"
        
deploy-backend:
    image: google/cloud-sdk:alpine
    stage: deploy
    script:
        - gcloud config set project $PROJECT_ID
        - gcloud auth activate-service-account --key-file $GCP_SERVICE_CREDS
        - gcloud builds submit --tag gcr.io/verdant-bus-276716/favemunchies
        - gcloud run deploy favemunchies --set-env-vars NODE_ENV='production',MONGODBURI=$MONGODBURI,GOOGLE_OAUTH_SECRET=$GOOGLE_OAUTH_SECRET --memory 512Mi --image gcr.io/verdant-bus-276716/favemunchies --platform managed --region us-west1 --allow-unauthenticated